@startuml
skinparam sequence {
ArrowColor black
LifeLineBorderColor black
LifeLineBackgroundColor khaki
ParticipantBackgroundColor lightgoldenrodyellow
}
Actor User
participant Front
participant Ad
participant 金服
participant 活动
participant Squirrel
participant MQ

User -> Front: 请求广告

activate Front
    Front -> Ad: 请求广告位（广告类型-67）
        activate Ad
        Ad -> Ad: 城市、周期、生效时段、渠道、\n频次、人群、实验等过滤
        Ad -> 金服: 查询用户是否已开通【免密】或【先用后付】
            activate 金服
                金服 --> Ad
            deactivate 金服
        opt 若用户已开通【免密】或【先用后付】
            Ad -> Ad: 过滤该广告
        end
        Ad -> 活动: tc查询用户是否命中
            activate 活动
                活动 --> Ad
            deactivate 活动
        opt 若不命中活动
            Ad -> Ad: 过滤该广告
        end
        Ad -> Ad: 数据封装及排序、优先级排序
        opt 若命中类型67广告
            Ad -> Squirrel: 上报至缓存，k:userId, v: adId+cityId
        end
        Ad --> Front: 广告数据返回
        deactivate Ad
    Front --> User: 展示广告
deactivate Front

User -> Front: 点击引导广告
activate Front
    Front -> 金服: 跳转至独立引导签约界面进行签约
        activate 金服
            金服 -> 金服: 签约
            金服 -> MQ: 发送签约成功消息
            activate MQ
            金服 --> Front: 返回打车
        deactivate 金服
    Front --> User: 继续打车流程
deactivate Front

MQ -> 活动: 签约成功消息
deactivate MQ
activate 活动
活动 -> Ad: 查询用户最近是否命中引导代扣广告及当时所在城市
    activate Ad
    Ad -> Squirrel: 查询用户最近是否命中引导代扣广告及相关信息
        activate Squirrel
        Squirrel --> Ad: 查询结果
        deactivate Squirrel
    Ad -> Ad: 判断是否是否命中缓存并组装返回结果
    Ad --> 活动: 返回用户命中引导代扣广告时所在城市
    deactivate Ad
alt 有城市
    活动 -> 活动: tca 发券
else 无城市
    活动 -> 活动: 不发券
end
deactivate 活动
@enduml