@startuml
skinparam sequence {
ArrowColor black
LifeLineBorderColor black
LifeLineBackgroundColor khaki
ParticipantBackgroundColor lightgoldenrodyellow
}
Actor User
participant Front
participant Ads
participant Promotion

User -> Front: 进入打车首页

activate Front
    Front -> Ads: 请求广告位（广告类型-62）
        activate Ads
        Ads -> Ads: 城市、周期、生效时段、渠道、\n频次、人群、实验等过滤
        Ads -> Promotion: 渠道活动组预领券
            activate Promotion
                Promotion --> Ads : 命中活动及券信息
            deactivate Promotion
        alt 命中活动且有券
            Ads -> Ads: 【是否有红包】字段置为 true
            opt 若广告位是【瓷片2区】（lion配置）
                Ads -> Ads : 将红包返回文案放至瓷片广告文案字段中
            end
        else 没命中活动或没券
            Ads -> Ads : 【是否有红包】字段为 false 或不设值
        end
        Ads -> Ads: 数据封装及排序、优先级排序
        Ads -> Front: 广告数据返回
        deactivate Ads
Front -> User: 展示广告
deactivate Front

@enduml