@startuml
skinparam sequence {
ArrowColor black
LifeLineBorderColor black
LifeLineBackgroundColor khaki
ParticipantBackgroundColor lightgoldenrodyellow
}


participant 库存服务
entity 分布式锁squirrel
database 流水DB

库存服务 -> 流水DB: 查看是否有该流水（扣减or回滚）
activate 流水DB
    流水DB --> 库存服务
deactivate 流水DB

opt 有流水记录
    库存服务 -> 库存服务: 消费完成
end 无流水记录

库存服务 -> 流水DB: 写流水
activate 流水DB
    流水DB --> 库存服务
deactivate 流水DB

opt 流水写入成功
    库存服务 -> 分布式锁squirrel:释放扣减时加的分布式锁
end
@enduml