@startuml
skinparam DatabaseBackgroundColor #FFE6F0
skinparam EntityBackgroundColor #FFE6F0
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor #FFE6F0
    ParticipantBackgroundColor #FFE6F0
}

participant 消费库存耗尽MQ as CMQ
entity 分布式锁 as DL
entity rule缓存 as RC
database ruleDB as DB
entity 补贴库存耗尽恢复通知MQ as SMQ

CMQ -> CMQ: 解析MQ消息\n获取bizKey和depletedTime

CMQ -> DL++: 加分布式锁（bizKey+quotaType）
return

CMQ -> RC++: 查询rule缓存
return

alt 若rule缓存不存在
    CMQ -> CMQ: 缓存异常日志并打点，返回成功
else 若rule缓存已打耗尽标识（depleted_time > 0）
    CMQ -> CMQ: 说明已被处理过，不再处理，直接返回成功
else 若rule缓存未打耗尽标识（depleted_time == 0）
    CMQ -> CMQ: 查询库存已消耗值，判断并设置库存耗尽标识字段
    CMQ -> DB++: 更新rule.depleted_time（更新为MQ消息中的depletedTime时间戳）
    return

    CMQ -> RC++: 更新rule缓存（设置depletedTime）
    return

    alt #E6FFE6 若是补贴库存
        CMQ -> SMQ: 发送MQ通知补贴库存状态变更【**耗尽**】
    end
end

CMQ -> DL: 释放锁
@enduml
