@startuml
skinparam DatabaseBackgroundColor lightgoldenrodyellow
skinparam EntityBackgroundColor lightgoldenrodyellow
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor khaki
    ParticipantBackgroundColor lightgoldenrodyellow
}

participant "ClcQuotaDeductDomainServiceImpl" as CQDSI
participant "QuotaConsumedQueryService" as QCQS
participant "QuotaMccConfig" as QMC
participant "SubsidyQuotaDeductService" as SQDS
participant "SubsidyQuotaQueryService" as SQQS
participant "QuotaDeductKvBaseComponent" as QDKBC
participant "ShardQuotaLocalCacheService" as SQLCS
participant "ShardQuotaKvService" as SQKS

CQDSI -> CQDSI++: 库存扣减接口-batchAtomicDeductQuota

group 查询校验阶段
    CQDSI -> CQDSI++--: 1.入参校验-validateAndCollectFailedDeductResponses

    CQDSI -> QCQS++: 2.查询库存-queryConsumedStock
        QCQS -> QCQS++--: 2.1.单独查补贴库存-processSubsidyQuotaKeys
        QCQS -> QCQS++--: 2.2.查询配置&用户库存-queryStock
    return

    CQDSI -> CQDSI++--: 3.复用校验接口（带查询结果，不会重复查询）-batchValidateQuota
    CQDSI -> CQDSI++--: 4.处理校验结果-processAtomicDeductInfoList
end

group 扣减阶段
    CQDSI -> CQDSI++: 5.扣减-atomicDeductQuota
        CQDSI -> SQDS++: 5.1.扣减补贴维度-deductSubsidyQuota
        return

        CQDSI -> CQDSI++: 5.2.扣减配置&用户维度-atomicDeductQuotas

            group 查询已扣减库存
                CQDSI -> CQDSI++: 5.2.1.查询已扣减库存（扣减、回滚复用方法）-queryQuotaDeductedDetail
                    CQDSI -> SQQS++: 5.2.1.1.查询补贴已扣减库存（回滚需要用）-querySubsidyQuotaConsumed
                    return
                    CQDSI -> QDKBC++: 5.2.1.2.查配置普通已扣减库存-batchQueryHasDeductedQuota
                    return
                    CQDSI -> SQLCS++: 5.2.1.3.查配置热点已扣减库存-queryBucketQuotaDetail
                    return
                    CQDSI -> CQDSI++--: 5.2.1.4.查用户已扣减库存-batchQueryUserHasDeductedQuota
                deactivate
            end

            group 执行扣减
                CQDSI -> CQDSI++: 5.2.2.配置库存扣减&失败回退-atomicDeductConfigQuota
                    ' 当校验时2个地域库存都充足时，若一个地域扣减失败，会重试另一个地域；
                    CQDSI -> QDKBC++: 5.2.2.1.扣减配置普通-atomicQuotaBatchDeductNormalConfig\n（每个key调一次squirrel lua，(每个key调一次cellar，多个key异步并发调用）
                    return
                    CQDSI -> SQKS++: 5.2.2.2.扣减配置热点-batchDeduct\n（每个key调一次squirrel lua，(每个key调一次cellar，多个key异步并发调用）
                    return
                deactivate

                CQDSI -> CQDSI++--: 5.2.3.扣减用户库存-atomicDeductUserQuota\n(每个key调一次cellar，多个key线程池异步并发调用)
            end

        deactivate

    deactivate

    CQDSI -> CQDSI++--: 6.executeParallelDeduct
end

note over CQDSI: 耗尽标识处理
alt 若扣减后库存耗尽
    CQDSI -> CQDSI++--: 发MQ异步更新rule耗尽标识
end

deactivate

@enduml