@startuml
skinparam sequence {
    ArrowColor black
    LifeLineBorderColor black
    LifeLineBackgroundColor khaki
    ParticipantBackgroundColor lightgoldenrodyellow
}

participant Actor
participant Next
participant Manage
participant Group
participant 龙门
participant Qualify
participant 风控
participant 审批流

Actor -> Next : save
activate Next

    Next -> Next : hasTemplatePermission-权限校验
    activate Next
    deactivate Next

    Next -> Next : genCouponGroup-生成待保存的券批次信息
    activate Next

        Next -> Next : validate-元数据层面校验（是否必填等基础校验+个性化校验）
        activate Next
        deactivate Next

        Next -> Next : validateGeneralCoupon-通用券严格校验
        activate Next
        deactivate Next

    deactivate Next

    Next -> Next : createCouponGroup-保存券批次
    activate Next

        Next -> 龙门 : validateBudget-校验预算
        activate 龙门
        龙门 --> Next
        deactivate 龙门

        ' 详细展开Manage的创建流程
        Next -> Manage : 保存
        activate Manage

            Manage -> Manage : querySimpleTemplateById-查模板信息
            activate Manage
            deactivate Manage

            Manage -> Manage : create-创建券批次
            activate Manage

                Manage -> Manage : couponGroupModelCheck-模型校验
                activate Manage
                deactivate Manage

                Manage -> Manage : createCouponGroupDc
                activate Manage

                    Manage -> 龙门 : 预创建 AN
                    activate 龙门
                    龙门 --> Manage
                    deactivate 龙门

                    Manage -> Group : createCouponGroupWithResult-创建券批次
                    activate Group
                    Group --> Manage
                    deactivate Group

                    Manage -> Manage : 插入券批次记录数据
                    activate Manage
                    deactivate Manage

                deactivate Manage

                Manage -> Manage : createAN-创建AN
                activate Manage

                    Manage -> 龙门 : saveDistInfo-保存分摊信息
                    activate 龙门
                    龙门 --> Manage
                    deactivate 龙门

                deactivate Manage

                Manage -> Manage : bindShareRule-绑定共享规则
                activate Manage

                    Manage -> Qualify : loadShareRule-加载共享规则
                    activate Qualify
                    Qualify --> Manage
                    deactivate Qualify

                    Manage -> Manage : 保存关联共享规则
                    activate Manage
                    deactivate Manage

                deactivate Manage

                Manage -> Manage : bindDynamicStrategy-绑定动态策略
                activate Manage
                deactivate Manage

                Manage -> Manage : saveDraft-保存草稿信息
                activate Manage
                deactivate Manage

                Manage -> 风控 : validateText-校验文案
                activate 风控
                风控 --> Manage
                deactivate 风控

                Manage -> Manage : asyncCompareCreateCouponGroup-建券异步比对
                activate Manage
                deactivate Manage

                Manage -> 审批流 : submitAudit-提交审批流
                activate 审批流
                审批流 --> Manage
                deactivate 审批流

            deactivate Manage

        deactivate Manage
        Manage --> Next

    deactivate Next

    Next -> Next : modifyCouponGroup-修改券批次
    activate Next

        Next -> 龙门 : validateBudget-校验预算
        activate 龙门
        龙门 --> Next
        deactivate 龙门

        Next -> Next : validOldCouponGroup-校验修改权限
        activate Next
        deactivate Next

        Next -> Manage : 保存
        activate Manage
        Manage --> Next
        deactivate Manage

    deactivate Next

    Next -> Next : asyncCompare4New
    activate Next
    deactivate Next

Next --> Actor
deactivate Next
@enduml
