@startuml
skinparam sequence {
ArrowColor black
LifeLineBorderColor black
LifeLineBackgroundColor khaki
ParticipantBackgroundColor lightgoldenrodyellow
}
participant Actor
Actor -> AdsManageServiceImpl : getBannerList
activate AdsManageServiceImpl
AdsManageServiceImpl -> AdsManagerConvert : 参数转换-getBannerSearchQcsVOV2
activate AdsManagerConvert
AdsManagerConvert --> AdsManageServiceImpl
deactivate AdsManagerConvert
AdsManageServiceImpl -> IBannerInfoService : 查询数量-getBannerInfoCount
activate IBannerInfoService
IBannerInfoService --> AdsManageServiceImpl
deactivate IBannerInfoService
AdsManageServiceImpl -> IBannerInfoService : 分页查询广告列表-getBannerInfoList
activate IBannerInfoService
IBannerInfoService --> AdsManageServiceImpl
deactivate IBannerInfoService
return
@enduml