@startuml
participant Actor
Actor -> PassengerShowBannerService : getBannerForPassengerV4
activate PassengerShowBannerService
PassengerShowBannerService -> CheckParamService : isParamValid
activate CheckParamService
CheckParamService --> PassengerShowBannerService
deactivate CheckParamService
PassengerShowBannerService -> CheckParamService : checkDefaultPosition
activate CheckParamService
CheckParamService --> PassengerShowBannerService
deactivate CheckParamService
PassengerShowBannerService -> ApiRequestConvert : convertCapiRequestToSearchVo
activate ApiRequestConvert
ApiRequestConvert --> PassengerShowBannerService
deactivate ApiRequestConvert
PassengerShowBannerService -> PassengerShowBannerService : removeNotAllowedLocation
activate PassengerShowBannerService
PassengerShowBannerService --> PassengerShowBannerService
deactivate PassengerShowBannerService
PassengerShowBannerService -> PassengerShowBannerDataService : getBannerForPassenger
activate PassengerShowBannerDataService
PassengerShowBannerDataService -> PassengerShowBannerDataService : asyncSendCoupon
activate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerDataService
deactivate PassengerShowBannerDataService
PassengerShowBannerDataService -> PrepareDataService : prepareCapiData
activate PrepareDataService
PrepareDataService -> ILocalCacheService : getBannerInfoPOListByLocationIdList
activate ILocalCacheService
ILocalCacheService --> PrepareDataService
deactivate ILocalCacheService
PrepareDataService -> PrepareDataService : filterPoList
activate PrepareDataService
PrepareDataService -> BannerInfoV2PO : isCityMatch
activate BannerInfoV2PO
BannerInfoV2PO --> PrepareDataService
deactivate BannerInfoV2PO
PrepareDataService -> BannerInfoV2PO : isBusinessIdMatchForPassenger
activate BannerInfoV2PO
BannerInfoV2PO --> PrepareDataService
deactivate BannerInfoV2PO
PrepareDataService -> BannerInfoV2PO : isChannelIdMatch
activate BannerInfoV2PO
BannerInfoV2PO --> PrepareDataService
deactivate BannerInfoV2PO
PrepareDataService -> BannerInfoV2PO : isChannelCodeMatch
activate BannerInfoV2PO
BannerInfoV2PO --> PrepareDataService
deactivate BannerInfoV2PO
PrepareDataService -> BannerInfoV2PO : isloginedVisible
activate BannerInfoV2PO
BannerInfoV2PO --> PrepareDataService
deactivate BannerInfoV2PO
PrepareDataService -> BannerInfoV2PO : isMtAdMatch
activate BannerInfoV2PO
BannerInfoV2PO --> PrepareDataService
deactivate BannerInfoV2PO
PrepareDataService --> PrepareDataService
deactivate PrepareDataService
PrepareDataService -> PrepareDataService : mergeLocationAndInfo
activate PrepareDataService
PrepareDataService --> PrepareDataService
deactivate PrepareDataService
PrepareDataService -> PrepareContextService : preparePassengerFilterContext
activate PrepareContextService
PrepareContextService -> PrepareContextService : buildNeededParamSet
activate PrepareContextService
PrepareContextService --> PrepareContextService
deactivate PrepareContextService
PrepareContextService -> PrepareContextService : buildOrderCategoryList
activate PrepareContextService
PrepareContextService --> PrepareContextService
deactivate PrepareContextService
PrepareContextService -> PrepareContextService : queryOrderInfo
activate PrepareContextService
PrepareContextService --> PrepareContextService
deactivate PrepareContextService
PrepareContextService -> PrepareContextService : buildContextFromOrderResponse
activate PrepareContextService
PrepareContextService --> PrepareContextService
deactivate PrepareContextService
PrepareContextService --> PrepareDataService
deactivate PrepareContextService
PrepareDataService --> PassengerShowBannerDataService
deactivate PrepareDataService
PassengerShowBannerDataService -> PassengerShowBannerDataService : filterAndConvertForCV2
activate PassengerShowBannerDataService
PassengerShowBannerDataService -> PassengerBannerFilterChainService : bannerFilter
activate PassengerBannerFilterChainService
PassengerBannerFilterChainService --> PassengerShowBannerDataService
deactivate PassengerBannerFilterChainService
PassengerShowBannerDataService -> CouponAggregationDataService : aggregationBannerDataPreQueryCoupon
activate CouponAggregationDataService
CouponAggregationDataService -> CouponAggregationDataService : queryDailyCouponData
activate CouponAggregationDataService
CouponAggregationDataService --> CouponAggregationDataService
deactivate CouponAggregationDataService
CouponAggregationDataService -> CouponAggregationDataService : filterAndAggregation
activate CouponAggregationDataService
CouponAggregationDataService -> CouponAggregationDataService : queryAndGetDailyCouponData
activate CouponAggregationDataService
CouponAggregationDataService --> CouponAggregationDataService
deactivate CouponAggregationDataService
CouponAggregationDataService --> CouponAggregationDataService
deactivate CouponAggregationDataService
CouponAggregationDataService --> PassengerShowBannerDataService
deactivate CouponAggregationDataService
PassengerShowBannerDataService -> PassengerShowBannerDataService : convertForCV2
activate PassengerShowBannerDataService
PassengerShowBannerDataService -> BannerInfoV2PO : divideByLocation
activate BannerInfoV2PO
BannerInfoV2PO --> PassengerShowBannerDataService
deactivate BannerInfoV2PO
PassengerShowBannerDataService -> PassengerShowBannerDataService : sortAndSiftByTab
activate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerDataService
deactivate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerDataService
deactivate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerDataService
deactivate PassengerShowBannerDataService
PassengerShowBannerDataService -> PassengerShowBannerDataService : generateLocationCodeAndFrameListMap
activate PassengerShowBannerDataService
PassengerShowBannerDataService -> PassengerShowBannerDataService : processBannersToFrames
activate PassengerShowBannerDataService
PassengerShowBannerDataService -> PassengerShowBannerDataService : initializeFrameQueues
activate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerDataService
deactivate PassengerShowBannerDataService
PassengerShowBannerDataService -> PassengerShowBannerDataService : processFrameQueueList
activate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerDataService
deactivate PassengerShowBannerDataService
PassengerShowBannerDataService -> PassengerShowBannerDataService : extractFirstFrameFromEachQueue
activate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerDataService
deactivate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerDataService
deactivate PassengerShowBannerDataService
PassengerShowBannerDataService -> PassengerShowBannerDataService : filterFirstFrameIfSpecialType
activate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerDataService
deactivate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerDataService
deactivate PassengerShowBannerDataService
PassengerShowBannerDataService --> PassengerShowBannerService
deactivate PassengerShowBannerDataService
PassengerShowBannerService -> CouponAggregationDataService : aggregationBannerDataFinally
activate CouponAggregationDataService
CouponAggregationDataService -> CouponAggregationDataService : queryAndGetDailyCouponData
activate CouponAggregationDataService
CouponAggregationDataService --> CouponAggregationDataService
deactivate CouponAggregationDataService
CouponAggregationDataService --> PassengerShowBannerService
deactivate CouponAggregationDataService
PassengerShowBannerService -> JumpUrlProcessService : processJumpUrl
activate JumpUrlProcessService
JumpUrlProcessService --> PassengerShowBannerService
deactivate JumpUrlProcessService
return
@enduml